<?xml version="1.0" encoding="UTF-8"?>
<!-- En esta parte defino el dtd de forma interna para validar el archivo xml-->
<!DOCTYPE etiqueta [
    <!ELEMENT etiqueta (nombre, calle, ciudad, pais, codigo)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT calle (#PCDATA)>
    <!ELEMENT ciudad (#PCDATA)>
    <!ELEMENT pais (#PCDATA)>
    <!ELEMENT codigo (#PCDATA)>
]>
<etiqueta>
    <nombre>Roberto García</nombre>
    <calle>c/ Mayor, 27</calle>
    <ciudad>Coslada</ciudad>
    <pais>España</pais>
    <codigo>39343</codigo>
</etiqueta>